### ISSUE TITLE
Cover Page 

### ISSUE THREAD

**Issue by kamrul4188** [kamrul4188/TE3201-Software-Engineering#2]
**The cover page needs to include the following:** 

1. Product name 
2. Name of the team members
3. NUS Logo
4. Module Name
5. Prof Name 
6. If you have anything to add

**Comment by Abdullah-A0147365Y** [comment]
I am working on this

**Comment by Abdullah-A0147365Y** [comment]
> **The cover page needs to include the following:**
> 
> 1. Product name
> 2. Name of the team members
> 3. NUS Logo
> 4. Module Name
> 5. Prof Name
> 6. If you have anything to add

[Project-AMYCA (Cover Page).docx](https://github.com/kamrul4188/TE3201-Software-Engineering/files/2897662/Project-AMYCA.Cover.Page.docx)
Dear All, Please check the attached cover page. If require to change please do so. Thanks

**Comment by kamrul4188** [comment]
okay Thanks
